### PR TITLE
optimized "dependsOn" path calculation routine to use BFS algorithm

### PR DESCRIPTION
**Pull request by okornev**
… to find shortest path instead of recursive backtracking that gives a random path. Deployment plan generation time significantly reduced on very complex designs with many relationships.

New algorithm can be disabled in runtime using system property -Dcom.oneops.transistor.bfsOptimization=false

### CODE REVIEW

**Comment by vitaliyzinchenko** [comment]
Looking good to me

**Comment by vitaliyzinchenko** [comment]
This is really really bad practice to do a DB call on every dpmt generate user call and based on this decide the implementation, it is not a business logic. It should be done via -D pro during startup. If you push this to Open Source version it would be embarrassing.

**Comment by lkhusid** [comment]
I strongly second that.   I do not see any sensible reason to use "heavy" (performance expensive) CMS variable construct to as a "just in case..." safety switch.    "-D" option is the way to go.
On another note, it is quite satisfying to see this optimization to make such a significant performance impact exceeding our even most optimistic expectations when we "brain stormed" to come up with things to try before implementation.
Aslo, as discussed, DB read/writes optimization (specifically in relation to RFC writes) should be a next logical step in picking up the performance - as it will benefit not only in deployment generation area  but throughout (incl. design pull, design and env load, platform creation and etc.).

**Comment by gauravlall** [comment]
1. The variable is cached and we can improve the caching capability to cache per vars .
2. The variable facilitates testing and rollout  of the feature in lower environment , where you can compare the plans before /after the change. 
3. Eventually after the rollout , we can get rid of the variable .
4. In some prior releases we had issues where we need to rollback some of changes which a -D would require a **deployment** on *tomcat* (corresponding artifact) , which makes rollback changes difficult.

**Pull request merged**
